server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: info

positions:
  filename: /run/promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    batchwait: 5s
    batchsize: 1048576

scrape_configs:

  - job_name: docker_files
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*-json.log

    pipeline_stages:
      # Каждая строка в json-file Docker — это:
      # {"log":"<actual log line>\n","stream":"stdout","time":"..."}
      - json:
          expressions:
            log_line: log
            stream: stream
      - output:
          source: log_line
      - labels:
          stream:
      # Для строк которые сами являются JSON (наши логи из FastAPI)
      # извлекаем level и logger как labels
      - json:
          expressions:
            level: level
            logger: logger
      - labels:
          level:
          logger:
